In [40]:
import pandas as pd


# Delete the columns Time, Sub_metering_2 and Sub_metering_3

df = pd.read_csv("./data/household_power_consumption.txt", sep=";")
df.drop(["Time", "Sub_metering_2", "Sub_metering_3"], inplace=True, axis=1)
df

/tmp/ipykernel_200906/1618705980.py:6: DtypeWarning: Columns (0: Global_active_power, 1: Global_reactive_power, 2: Voltage, 3: Global_intensity, 4: Sub_metering_1, 5: Sub_metering_2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./data/household_power_consumption.txt", sep=";")

,Date,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
0,16/12/2006,4.216,0.418,234.840,18.400,0.000
1,16/12/2006,5.360,0.436,233.630,23.000,0.000
2,16/12/2006,5.374,0.498,233.290,23.000,0.000
3,16/12/2006,5.388,0.502,233.740,23.000,0.000
4,16/12/2006,3.666,0.528,235.680,15.800,0.000
...,...,...,...,...,...,...
2075254,26/11/2010,0.946,0.0,240.43,4.0,0.0
2075255,26/11/2010,0.944,0.0,240.0,4.0,0.0
2075256,26/11/2010,0.938,0.0,239.82,3.8,0.0
2075257,26/11/2010,0.934,0.0,239.7,3.8,0.0
2075258,26/11/2010,0.932,0.0,239.55,3.8,0.0

In [41]:
# Set Date as index

df.set_index("Date", inplace=True)
df.index = pd.to_datetime(df.index, dayfirst=True)
df.index = df.index.astype("datetime64[ns]")
# df.index = df.index.strftime("%Y-%m-%d %H:%M:%S")
print(df.index.dtype)
df

datetime64[ns]

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
Date,,,,,
2006-12-16,4.216,0.418,234.840,18.400,0.000
2006-12-16,5.360,0.436,233.630,23.000,0.000
2006-12-16,5.374,0.498,233.290,23.000,0.000
2006-12-16,5.388,0.502,233.740,23.000,0.000
2006-12-16,3.666,0.528,235.680,15.800,0.000
...,...,...,...,...,...
2010-11-26,0.946,0.0,240.43,4.0,0.0
2010-11-26,0.944,0.0,240.0,4.0,0.0
2010-11-26,0.938,0.0,239.82,3.8,0.0
2010-11-26,0.934,0.0,239.7,3.8,0.0
2010-11-26,0.932,0.0,239.55,3.8,0.0

In [42]:
# DataFrame with updated types:


def update_types(df):
    df = df.replace("?", "nan")
    df["Global_active_power"] = df["Global_active_power"].astype(float)
    df["Global_reactive_power"] = df["Global_reactive_power"].astype(float)
    df["Voltage"] = df["Voltage"].astype(float)
    df["Global_intensity"] = df["Global_intensity"].astype(float)
    df["Sub_metering_1"] = df["Sub_metering_1"].astype(float)
    return df

df = update_types(df)
print(df.dtypes)

Global_active_power      float64
Global_reactive_power    float64
Voltage                  float64
Global_intensity         float64
Sub_metering_1           float64
dtype: object

In [43]:
df.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
count,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06
mean,1.091615e+00,1.237145e-01,2.408399e+02,4.627759e+00,1.121923e+00
std,1.057294e+00,1.127220e-01,3.239987e+00,4.444396e+00,6.153031e+00
min,7.600000e-02,0.000000e+00,2.232000e+02,2.000000e-01,0.000000e+00
25%,3.080000e-01,4.800000e-02,2.389900e+02,1.400000e+00,0.000000e+00
50%,6.020000e-01,1.000000e-01,2.410100e+02,2.600000e+00,0.000000e+00
75%,1.528000e+00,1.940000e-01,2.428900e+02,6.400000e+00,0.000000e+00
max,1.112200e+01,1.390000e+00,2.541500e+02,4.840000e+01,8.800000e+01

In [44]:
# Delete the rows with missing values

print("before:\n",df.isna().sum())

df.dropna(inplace=True)

print("----\nafter\n",df.isna().sum())
# df

before:
 Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
dtype: int64
----
after
 Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
dtype: int64

In [45]:
# Modify Sub_metering_1 by adding 1 to it and multiplying the total by 0.06.
# (x+1)*0.06

df.loc[:, "Sub_metering_1"] = (df["Sub_metering_1"] + 1) * 0.06

print(df["Sub_metering_1"].head())

Date
2006-12-16    0.06
2006-12-16    0.06
2006-12-16    0.06
2006-12-16    0.06
2006-12-16    0.06
Name: Sub_metering_1, dtype: float64

In [46]:
# Select all the rows for which the Date >= 2008-12-27, and Voltage >= 242
res = df[(df.index >= "2008-12-27") & (df["Voltage"] >= 242.0)]
print(res.shape)
res
print(res[["Global_active_power", "Global_reactive_power"]].head().to_markdown())

(449667, 5)
| Date                |   Global_active_power |   Global_reactive_power |
|:--------------------|----------------------:|------------------------:|
| 2008-12-27 00:00:00 |                 0.996 |                   0.066 |
| 2008-12-27 00:00:00 |                 1.076 |                   0.162 |
| 2008-12-27 00:00:00 |                 1.064 |                   0.172 |
| 2008-12-27 00:00:00 |                 1.07  |                   0.174 |
| 2008-12-27 00:00:00 |                 0.804 |                   0.184 |

In [47]:
# Print the 88888th row.

print(df.iloc[88887])

Global_active_power        0.254
Global_reactive_power      0.000
Voltage                  238.100
Global_intensity           1.200
Sub_metering_1             0.060
Name: 2007-02-16 00:00:00, dtype: float64

In [48]:
# the date for the Global_active_power is maximal

date = df["Global_active_power"].idxmax()
print(date)

2009-02-22 00:00:00

In [49]:
# Sort the first three columns by descending order of Global_active_power and ascending order of Voltage

three_col = df.iloc[:, :3]
sorted = three_col.sort_values(by=["Global_active_power", "Voltage"], ascending=[False, True])
print(sorted.tail().to_markdown())

| Date                |   Global_active_power |   Global_reactive_power |   Voltage |
|:--------------------|----------------------:|------------------------:|----------:|
| 2008-08-28 00:00:00 |                 0.076 |                       0 |    234.88 |
| 2008-08-28 00:00:00 |                 0.076 |                       0 |    235.18 |
| 2008-08-28 00:00:00 |                 0.076 |                       0 |    235.4  |
| 2008-08-28 00:00:00 |                 0.076 |                       0 |    235.64 |
| 2008-08-12 00:00:00 |                 0.076 |                       0 |    236.5  |

In [50]:
# Compute the daily average of Global_active_power.

d_avg = df["Global_active_power"].groupby(df.index).mean()
print(d_avg)

Date
2006-12-16    3.053475
2006-12-17    2.354486
2006-12-18    1.530435
2006-12-19    1.157079
2006-12-20    1.545658
                ...
2010-11-22    1.417733
2010-11-23    1.095511
2010-11-24    1.247394
2010-11-25    0.993864
2010-11-26    1.178230
Name: Global_active_power, Length: 1433, dtype: float64