In [13]:
import pandas as pd

# Preliminary: Drop the flower column
df = pd.read_csv("./data/iris.csv")
col = df.columns
print(col)
df.drop("flower", axis=1)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'flower'], dtype='str')

    sepal_length sepal_width petal_length petal_width
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0        -3.6         -1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [16]:
# Fill the missing values with : sepal_length -> mean
# Fill the missing values with : sepal_width -> median
# Fill the missing values with : petal_length, petal_width -> 0


# pd.to_numeric(df.loc[:,col], errors='coerce')
df["sepal_length"] = pd.to_numeric(df["sepal_length"], errors="coerce")
df["sepal_width"] = pd.to_numeric(df["sepal_width"], errors="coerce")
df["petal_length"] = pd.to_numeric(df["petal_length"], errors="coerce")
df["petal_width"] = pd.to_numeric(df["petal_width"], errors="coerce")

# df["sepal_length"].fillna(df["sepal_length"].mean())
# df["sepal_width"].fillna(df["sepal_width"].median())
# df["petal_length"].fillna(0)
# df["petal_length"].fillna(0)
# df

df.fillna({
    "sepal_length" : df["sepal_length"].mean(),
    "sepal_width" : df["sepal_width"].median(),
    "petal_length" : 0,
    "petal_width" : 0,
})
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    146.000000   141.000000    120.000000   147.000000
mean      56.907534    52.625532     15.529167    12.026531
std      572.222221   417.127170    127.459631   131.873447
min       -4.400000    -3.600000     -4.800000    -2.500000
25%        5.100000     2.800000      2.725000     0.300000
50%        5.750000     3.000000      4.500000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max     6900.000000  3809.000000   1400.000000  1600.000000